name: Deploy to Firebase Hosting

on:
  push:
    branches: [ master ]  # Trigger on pushes to the main branch
  pull_request:  # Optionally trigger on pull requests
    branches: [ master ]
    paths:
      - 'public/**'  # Only trigger on changes in the public directory (adjust as needed)

jobs:
  build:
    runs-on: ubuntu-latest  # Or a different OS that suits your project
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/firebase-hosting-deploy@v1
        with:
          token: ${{ secrets.FIREBASE_TOKEN }}  # Store token securely in GitHub secrets
          firebase_project: ${{ secrets.FIREBASE_PROJECT_ID }}  # Store project ID in secrets
          # Optional arguments
         # use_app_distribution: false  # Set to true for App Distribution
          # site: rkjshello  # If you're deploying to a specific site, uncomment and specify the site name
